// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file translation.proto (package translation, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "./google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file translation.proto.
 */
export const file_translation: GenFile = /*@__PURE__*/
  fileDesc("ChF0cmFuc2xhdGlvbi5wcm90bxILdHJhbnNsYXRpb24idwoYR2V0U2Vuc2VUcmFuc2xhdGVSZXF1ZXN0EhAKCHNlbnNlX2lkGAEgASgJEhgKC2ZpbmdlcnByaW50GAIgASgJSACIAQESDAoEcGFnZRgDIAEoBRIRCglwYWdlX3NpemUYBCABKAVCDgoMX2ZpbmdlcnByaW50IjIKD1RyYW5zbGF0ZVJlY29yZBIMCgR0ZXh0GAEgASgJEhEKCXRyYW5zbGF0ZRgCIAEoCSLgAgoZR2V0U2Vuc2VUcmFuc2xhdGVSZXNwb25zZRJCCgZjb21tb24YASADKAsyMi50cmFuc2xhdGlvbi5HZXRTZW5zZVRyYW5zbGF0ZVJlc3BvbnNlLkNvbW1vbkVudHJ5EkQKB3NwZWNpYWwYAiADKAsyMy50cmFuc2xhdGlvbi5HZXRTZW5zZVRyYW5zbGF0ZVJlc3BvbnNlLlNwZWNpYWxFbnRyeRIMCgRwYWdlGAMgASgFEhEKCXBhZ2Vfc2l6ZRgEIAEoBRINCgV0b3RhbBgFIAEoAxITCgt0b3RhbF9wYWdlcxgGIAEoAxIVCg1zcGVjaWFsX3RvdGFsGAcgASgDGi0KC0NvbW1vbkVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaLgoMU3BlY2lhbEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEilQEKFlRyYW5zbGF0ZVN0cmVhbVJlcXVlc3QSDAoEdGV4dBgBIAEoCRIQCghzZW5zZV9pZBgCIAEoCRITCgtmaW5nZXJwcmludBgDIAEoCRIQCghzcmNfbGFuZxgGIAEoCRIQCghkc3RfbGFuZxgHIAEoCRIRCglmcm9tX2xhbmcYBCABKAkSDwoHdG9fbGFuZxgFIAEoCSLqAQoXVHJhbnNsYXRlU3RyZWFtUmVzcG9uc2USFQoNb3JpZ2luYWxfdGV4dBgBIAEoCRJKCgt0cmFuc2xhdGlvbhgCIAMoCzI1LnRyYW5zbGF0aW9uLlRyYW5zbGF0ZVN0cmVhbVJlc3BvbnNlLlRyYW5zbGF0aW9uRW50cnkSEQoJdGltZXN0YW1wGAMgASgDEhAKCGZpbmlzaGVkGAQgASgIEhMKC2JhdGNoX2luZGV4GAUgASgFGjIKEFRyYW5zbGF0aW9uRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ATKFAgoSVHJhbnNsYXRpb25TZXJ2aWNlEowBChFHZXRTZW5zZVRyYW5zbGF0ZRIlLnRyYW5zbGF0aW9uLkdldFNlbnNlVHJhbnNsYXRlUmVxdWVzdBomLnRyYW5zbGF0aW9uLkdldFNlbnNlVHJhbnNsYXRlUmVzcG9uc2UiKILT5JMCIhIgL3YxL3RyYW5zbGF0aW9uL3NlbnNlL3tzZW5zZV9pZH0SYAoPVHJhbnNsYXRlU3RyZWFtEiMudHJhbnNsYXRpb24uVHJhbnNsYXRlU3RyZWFtUmVxdWVzdBokLnRyYW5zbGF0aW9uLlRyYW5zbGF0ZVN0cmVhbVJlc3BvbnNlIgAwAUI0WjJhcGkubGFrZXIuZGV2L3Byb3RvL2dlbi9nby90cmFuc2xhdGlvbjt0cmFuc2xhdGlvbmIGcHJvdG8z", [file_google_api_annotations]);

/**
 * GetSenseTranslateRequest 查询指定sense的翻译请求
 *
 * @generated from message translation.GetSenseTranslateRequest
 */
export type GetSenseTranslateRequest = Message<"translation.GetSenseTranslateRequest"> & {
  /**
   * 语义sense ID，必填
   *
   * @generated from field: string sense_id = 1;
   */
  senseId: string;

  /**
   * 用户指纹，用于查询个性化翻译，可选
   *
   * @generated from field: optional string fingerprint = 2;
   */
  fingerprint?: string;

  /**
   * 页码，默认1
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * 每页大小，默认1000，最大5000
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;
};

/**
 * Describes the message translation.GetSenseTranslateRequest.
 * Use `create(GetSenseTranslateRequestSchema)` to create a new message.
 */
export const GetSenseTranslateRequestSchema: GenMessage<GetSenseTranslateRequest> = /*@__PURE__*/
  messageDesc(file_translation, 0);

/**
 * TranslateRecord 单条翻译记录
 *
 * @generated from message translation.TranslateRecord
 */
export type TranslateRecord = Message<"translation.TranslateRecord"> & {
  /**
   * 原文
   *
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * 译文
   *
   * @generated from field: string translate = 2;
   */
  translate: string;
};

/**
 * Describes the message translation.TranslateRecord.
 * Use `create(TranslateRecordSchema)` to create a new message.
 */
export const TranslateRecordSchema: GenMessage<TranslateRecord> = /*@__PURE__*/
  messageDesc(file_translation, 1);

/**
 * GetSenseTranslateResponse 翻译查询响应
 *
 * @generated from message translation.GetSenseTranslateResponse
 */
export type GetSenseTranslateResponse = Message<"translation.GetSenseTranslateResponse"> & {
  /**
   * 通用翻译，key是原文，value是译文
   *
   * @generated from field: map<string, string> common = 1;
   */
  common: { [key: string]: string };

  /**
   * 个性化翻译，key是原文，value是译文，只有提供fingerprint时才有
   *
   * @generated from field: map<string, string> special = 2;
   */
  special: { [key: string]: string };

  /**
   * 当前页码
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * 每页大小
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;

  /**
   * 总记录数
   *
   * @generated from field: int64 total = 5;
   */
  total: bigint;

  /**
   * 总页数
   *
   * @generated from field: int64 total_pages = 6;
   */
  totalPages: bigint;

  /**
   * 个性化翻译总记录数，只有提供fingerprint时才有
   *
   * @generated from field: int64 special_total = 7;
   */
  specialTotal: bigint;
};

/**
 * Describes the message translation.GetSenseTranslateResponse.
 * Use `create(GetSenseTranslateResponseSchema)` to create a new message.
 */
export const GetSenseTranslateResponseSchema: GenMessage<GetSenseTranslateResponse> = /*@__PURE__*/
  messageDesc(file_translation, 2);

/**
 * TranslateStreamRequest 流式翻译请求
 *
 * @generated from message translation.TranslateStreamRequest
 */
export type TranslateStreamRequest = Message<"translation.TranslateStreamRequest"> & {
  /**
   * 用户输入文本（可选，用于上下文）
   *
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * 要查询的sense ID
   *
   * @generated from field: string sense_id = 2;
   */
  senseId: string;

  /**
   * 用户指纹，可选
   *
   * @generated from field: string fingerprint = 3;
   */
  fingerprint: string;

  /**
   * 源语言过滤，可选，只返回指定源语言的翻译
   *
   * @generated from field: string src_lang = 6;
   */
  srcLang: string;

  /**
   * 目标语言过滤，可选，只返回指定目标语言的翻译（预加载翻译池必填）
   *
   * @generated from field: string dst_lang = 7;
   */
  dstLang: string;

  /**
   * 源语言，可选，用于翻译
   *
   * @generated from field: string from_lang = 4;
   */
  fromLang: string;

  /**
   * 目标语言，必填，用于翻译
   *
   * @generated from field: string to_lang = 5;
   */
  toLang: string;
};

/**
 * Describes the message translation.TranslateStreamRequest.
 * Use `create(TranslateStreamRequestSchema)` to create a new message.
 */
export const TranslateStreamRequestSchema: GenMessage<TranslateStreamRequest> = /*@__PURE__*/
  messageDesc(file_translation, 3);

/**
 * TranslateStreamResponse 流式翻译响应
 *
 * @generated from message translation.TranslateStreamResponse
 */
export type TranslateStreamResponse = Message<"translation.TranslateStreamResponse"> & {
  /**
   * 原始请求文本
   *
   * @generated from field: string original_text = 1;
   */
  originalText: string;

  /**
   * 翻译结果，key是原文，value是译文
   *
   * @generated from field: map<string, string> translation = 2;
   */
  translation: { [key: string]: string };

  /**
   * 时间戳
   *
   * @generated from field: int64 timestamp = 3;
   */
  timestamp: bigint;

  /**
   * 是否是最后一条消息，完成标识
   *
   * @generated from field: bool finished = 4;
   */
  finished: boolean;

  /**
   * 当前批次序号，从0开始
   *
   * @generated from field: int32 batch_index = 5;
   */
  batchIndex: number;
};

/**
 * Describes the message translation.TranslateStreamResponse.
 * Use `create(TranslateStreamResponseSchema)` to create a new message.
 */
export const TranslateStreamResponseSchema: GenMessage<TranslateStreamResponse> = /*@__PURE__*/
  messageDesc(file_translation, 4);

/**
 * TranslationService 翻译服务
 * 提供统一的翻译查询接口，支持普通查询和流式推送
 *
 * @generated from service translation.TranslationService
 */
export const TranslationService: GenService<{
  /**
   * GetSenseTranslate 查询指定sense的翻译，一次性返回所有结果
   * 类似现有的REST API端点
   *
   * @generated from rpc translation.TranslationService.GetSenseTranslate
   */
  getSenseTranslate: {
    methodKind: "unary";
    input: typeof GetSenseTranslateRequestSchema;
    output: typeof GetSenseTranslateResponseSchema;
  },
  /**
   * TranslateStream 服务器流式推送翻译结果
   * 客户端发送一个查询请求，服务端逐条推送翻译结果
   * 适合大数据量实时推送场景
   *
   * @generated from rpc translation.TranslationService.TranslateStream
   */
  translateStream: {
    methodKind: "server_streaming";
    input: typeof TranslateStreamRequestSchema;
    output: typeof TranslateStreamResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_translation, 0);

