import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2';
import { file_google_protobuf_descriptor } from '@bufbuild/protobuf/wkt';
import { MethodKind, createClient } from '@connectrpc/connect';
import { createConnectTransport } from '@connectrpc/connect-web';
import { create as create$1 } from '@bufbuild/protobuf';

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/**
 * Describes the file google/api/http.proto.
 */
const file_google_api_http = /*@__PURE__*/ fileDesc("ChVnb29nbGUvYXBpL2h0dHAucHJvdG8SCmdvb2dsZS5hcGkiVAoESHR0cBIjCgVydWxlcxgBIAMoCzIULmdvb2dsZS5hcGkuSHR0cFJ1bGUSJwofZnVsbHlfZGVjb2RlX3Jlc2VydmVkX2V4cGFuc2lvbhgCIAEoCCKBAgoISHR0cFJ1bGUSEAoIc2VsZWN0b3IYASABKAkSDQoDZ2V0GAIgASgJSAASDQoDcHV0GAMgASgJSAASDgoEcG9zdBgEIAEoCUgAEhAKBmRlbGV0ZRgFIAEoCUgAEg8KBXBhdGNoGAYgASgJSAASLwoGY3VzdG9tGAggASgLMh0uZ29vZ2xlLmFwaS5DdXN0b21IdHRwUGF0dGVybkgAEgwKBGJvZHkYByABKAkSFQoNcmVzcG9uc2VfYm9keRgMIAEoCRIxChNhZGRpdGlvbmFsX2JpbmRpbmdzGAsgAygLMhQuZ29vZ2xlLmFwaS5IdHRwUnVsZUIJCgdwYXR0ZXJuIi8KEUN1c3RvbUh0dHBQYXR0ZXJuEgwKBGtpbmQYASABKAkSDAoEcGF0aBgCIAEoCUJnCg5jb20uZ29vZ2xlLmFwaUIJSHR0cFByb3RvUAFaQWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYXBpL2Fubm90YXRpb25zO2Fubm90YXRpb25zogIER0FQSWIGcHJvdG8z");

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/**
 * Describes the file google/api/annotations.proto.
 */
const file_google_api_annotations = /*@__PURE__*/ fileDesc("Chxnb29nbGUvYXBpL2Fubm90YXRpb25zLnByb3RvEgpnb29nbGUuYXBpOksKBGh0dHASHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxiwyrwiIAEoCzIULmdvb2dsZS5hcGkuSHR0cFJ1bGVSBGh0dHBCbgoOY29tLmdvb2dsZS5hcGlCEEFubm90YXRpb25zUHJvdG9QAVpBZ29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy9hcGkvYW5ub3RhdGlvbnM7YW5ub3RhdGlvbnOiAgRHQVBJYgZwcm90bzM", [file_google_api_http, file_google_protobuf_descriptor]);

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file proto/translation.proto (package translation, syntax proto3)
/* eslint-disable */
/**
 * Describes the file proto/translation.proto.
 */
const file_proto_translation = /*@__PURE__*/ fileDesc("Chdwcm90by90cmFuc2xhdGlvbi5wcm90bxILdHJhbnNsYXRpb24idwoYR2V0U2Vuc2VUcmFuc2xhdGVSZXF1ZXN0EhAKCHNlbnNlX2lkGAEgASgJEhgKC2ZpbmdlcnByaW50GAIgASgJSACIAQESDAoEcGFnZRgDIAEoBRIRCglwYWdlX3NpemUYBCABKAVCDgoMX2ZpbmdlcnByaW50IjIKD1RyYW5zbGF0ZVJlY29yZBIMCgR0ZXh0GAEgASgJEhEKCXRyYW5zbGF0ZRgCIAEoCSLgAgoZR2V0U2Vuc2VUcmFuc2xhdGVSZXNwb25zZRJCCgZjb21tb24YASADKAsyMi50cmFuc2xhdGlvbi5HZXRTZW5zZVRyYW5zbGF0ZVJlc3BvbnNlLkNvbW1vbkVudHJ5EkQKB3NwZWNpYWwYAiADKAsyMy50cmFuc2xhdGlvbi5HZXRTZW5zZVRyYW5zbGF0ZVJlc3BvbnNlLlNwZWNpYWxFbnRyeRIMCgRwYWdlGAMgASgFEhEKCXBhZ2Vfc2l6ZRgEIAEoBRINCgV0b3RhbBgFIAEoAxITCgt0b3RhbF9wYWdlcxgGIAEoAxIVCg1zcGVjaWFsX3RvdGFsGAcgASgDGi0KC0NvbW1vbkVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaLgoMU3BlY2lhbEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEilQEKFlRyYW5zbGF0ZVN0cmVhbVJlcXVlc3QSDAoEdGV4dBgBIAEoCRIQCghzZW5zZV9pZBgCIAEoCRITCgtmaW5nZXJwcmludBgDIAEoCRIQCghzcmNfbGFuZxgGIAEoCRIQCghkc3RfbGFuZxgHIAEoCRIRCglmcm9tX2xhbmcYBCABKAkSDwoHdG9fbGFuZxgFIAEoCSLqAQoXVHJhbnNsYXRlU3RyZWFtUmVzcG9uc2USFQoNb3JpZ2luYWxfdGV4dBgBIAEoCRJKCgt0cmFuc2xhdGlvbhgCIAMoCzI1LnRyYW5zbGF0aW9uLlRyYW5zbGF0ZVN0cmVhbVJlc3BvbnNlLlRyYW5zbGF0aW9uRW50cnkSEQoJdGltZXN0YW1wGAMgASgDEhAKCGZpbmlzaGVkGAQgASgIEhMKC2JhdGNoX2luZGV4GAUgASgFGjIKEFRyYW5zbGF0aW9uRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ATKFAgoSVHJhbnNsYXRpb25TZXJ2aWNlEowBChFHZXRTZW5zZVRyYW5zbGF0ZRIlLnRyYW5zbGF0aW9uLkdldFNlbnNlVHJhbnNsYXRlUmVxdWVzdBomLnRyYW5zbGF0aW9uLkdldFNlbnNlVHJhbnNsYXRlUmVzcG9uc2UiKILT5JMCIhIgL3YxL3RyYW5zbGF0aW9uL3NlbnNlL3tzZW5zZV9pZH0SYAoPVHJhbnNsYXRlU3RyZWFtEiMudHJhbnNsYXRpb24uVHJhbnNsYXRlU3RyZWFtUmVxdWVzdBokLnRyYW5zbGF0aW9uLlRyYW5zbGF0ZVN0cmVhbVJlc3BvbnNlIgAwAUI0WjJhcGkubGFrZXIuZGV2L3Byb3RvL2dlbi9nby90cmFuc2xhdGlvbjt0cmFuc2xhdGlvbmIGcHJvdG8z", [file_google_api_annotations]);
/**
 * Describes the message translation.GetSenseTranslateRequest.
 * Use `create(GetSenseTranslateRequestSchema)` to create a new message.
 */
const GetSenseTranslateRequestSchema = /*@__PURE__*/ messageDesc(file_proto_translation, 0);
/**
 * Describes the message translation.GetSenseTranslateResponse.
 * Use `create(GetSenseTranslateResponseSchema)` to create a new message.
 */
const GetSenseTranslateResponseSchema = /*@__PURE__*/ messageDesc(file_proto_translation, 2);
/**
 * Describes the message translation.TranslateStreamRequest.
 * Use `create(TranslateStreamRequestSchema)` to create a new message.
 */
const TranslateStreamRequestSchema = /*@__PURE__*/ messageDesc(file_proto_translation, 3);
/**
 * Describes the message translation.TranslateStreamResponse.
 * Use `create(TranslateStreamResponseSchema)` to create a new message.
 */
const TranslateStreamResponseSchema = /*@__PURE__*/ messageDesc(file_proto_translation, 4);

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file proto/translation.proto (package translation, syntax proto3)
/* eslint-disable */
// @ts-nocheck
/**
 * TranslationService 翻译服务
 * 提供统一的翻译查询接口，支持普通查询和流式推送
 *
 * @generated from service translation.TranslationService
 */
const TranslationService = {
    typeName: "translation.TranslationService",
    methods: {
        /**
         * GetSenseTranslate 查询指定sense的翻译，一次性返回所有结果
         * 类似现有的REST API端点
         *
         * @generated from rpc translation.TranslationService.GetSenseTranslate
         */
        getSenseTranslate: {
            name: "GetSenseTranslate",
            I: GetSenseTranslateRequestSchema,
            O: GetSenseTranslateResponseSchema,
            kind: MethodKind.Unary,
        },
        /**
         * TranslateStream 服务器流式推送翻译结果
         * 客户端发送一个查询请求，服务端逐条推送翻译结果
         * 适合大数据量实时推送场景
         *
         * @generated from rpc translation.TranslationService.TranslateStream
         */
        translateStream: {
            name: "TranslateStream",
            I: TranslateStreamRequestSchema,
            O: TranslateStreamResponseSchema,
            kind: MethodKind.ServerStreaming,
        },
    }
};

/**
 * Translation Service Connect RPC TypeScript/JavaScript Client
 *
 * Auto-generated for api.laker.dev Translation Service
 * Service: TranslationService
 * Source: proto/translation.proto
 *
 * This client uses Connect RPC for native HTTP streaming over HTTP/2
 * Supports true multiplexing on a single connection
 */
// Import generated Connect RPC code
function create(schema, json) {
    return create$1(schema, json);
}
const defaultCrossTabOptions = {
    enabled: false,
    channelName: 'laker-translation-cache',
    storageKeyPrefix: 'laker_translation_',
};
/**
 * Automatic template extraction from text containing numeric variables
 * @param text Original text that may contain numeric variables
 * @returns Template extraction result
 */
function extractTemplate(text) {
    const numberRegex = /\d+(?:\.\d+)?/g;
    const matches = text.match(numberRegex);
    if (!matches || matches.length === 0) {
        return {
            isTemplated: false,
            srcTemplate: text,
            dstTemplate: '',
            variables: [],
        };
    }
    let template = text;
    const variables = [];
    matches.forEach((match, index) => {
        const varName = `{var${index + 1}}`;
        template = template.replace(match, varName);
        variables.push(match);
    });
    return {
        isTemplated: variables.length > 0,
        srcTemplate: template,
        dstTemplate: '',
        variables,
    };
}
class TranslationPool {
    client;
    senseId;
    pools = new Map();
    currentFingerprint = null;
    currentToLang = null;
    crossTabOptions;
    broadcastChannel = null;
    loading = false;
    loadedCombinations = new Set();
    currentLanguageVersion = 0;
    queuedRequests = [];
    pendingResolutions = {};
    onTranslationLoaded = null;
    onPoolInitialized = null;
    onQueueProcessed = null;
    onTranslationUpdated = null;
    persistentStorage;
    backgroundUpdateOptions;
    backgroundUpdateTimer = null;
    entryMetadata = new Map();
    updateCallback = null;
    options;
    getPoolKey(fingerprint, toLang) {
        return `${fingerprint}:${toLang}`;
    }
    constructor(client, senseId, options) {
        this.client = client;
        this.senseId = senseId;
        // Set up crossTabOptions with defaults
        this.crossTabOptions = {
            ...defaultCrossTabOptions,
            ...options?.crossTab,
        };
        // Set up backgroundUpdateOptions with defaults
        this.backgroundUpdateOptions = {
            enabled: options?.backgroundUpdate?.enabled ?? false,
            intervalMs: options?.backgroundUpdate?.intervalMs ?? 5 * 60 * 1000,
            batchSize: options?.backgroundUpdate?.batchSize ?? 50,
            staleThresholdMs: options?.backgroundUpdate?.staleThresholdMs ?? 24 * 60 * 60 * 1000,
        };
        // Store full options including defaults for API access
        this.options = {
            ...options,
            senseId,
            crossTab: this.crossTabOptions,
            backgroundUpdate: this.backgroundUpdateOptions,
        };
        this.persistentStorage = options?.persistentStorage;
        if (this.crossTabOptions.enabled && typeof BroadcastChannel !== 'undefined') {
            this.initCrossTabSync();
        }
        this.loadFromStorage();
        this.startBackgroundUpdateChecker();
    }
    setTranslationLoadedCallback(callback) {
        this.onTranslationLoaded = callback;
    }
    setPoolInitializedCallback(callback) {
        this.onPoolInitialized = callback;
    }
    setQueueProcessedCallback(callback) {
        this.onQueueProcessed = callback;
    }
    setTranslationUpdatedCallback(callback) {
        this.onTranslationUpdated = callback;
    }
    initCrossTabSync() {
        this.broadcastChannel = new BroadcastChannel(this.crossTabOptions.channelName);
        this.broadcastChannel.onmessage = (event) => {
            const message = event.data;
            if (message.senseId !== this.senseId) {
                return;
            }
            switch (message.type) {
                case 'cache_update':
                    this.handleCacheUpdate(message);
                    break;
                case 'cache_clear':
                    this.handleCacheClear(message);
                    break;
                case 'request_initial_sync':
                    this.handleInitialSyncRequest();
                    break;
            }
        };
        this.broadcastChannel.postMessage({
            type: 'request_initial_sync',
            senseId: this.senseId,
        });
    }
    loadFromStorage() {
        if (typeof localStorage === 'undefined' || !this.crossTabOptions.enabled) {
            return;
        }
        const prefix = `${this.crossTabOptions.storageKeyPrefix}${this.senseId}_`;
        for (let i = 0; i < localStorage.length; i++) {
            const key = localStorage.key(i);
            if (key && key.startsWith(prefix) && key.includes(':')) {
                const afterPrefix = key.substring(prefix.length);
                const colonIndex = afterPrefix.lastIndexOf(':');
                if (colonIndex > 0) {
                    const fingerprint = afterPrefix.substring(0, colonIndex);
                    const toLang = afterPrefix.substring(colonIndex + 1);
                    if (fingerprint === 'common') {
                        this.loadLanguageFromStorage(fingerprint, toLang);
                    }
                }
            }
        }
    }
    loadLanguageFromStorage(fingerprint, toLang) {
        const poolKey = this.getPoolKey(fingerprint, toLang);
        const storageKey = this.getStorageKey(fingerprint, toLang);
        try {
            const stored = localStorage.getItem(storageKey);
            if (stored) {
                const data = JSON.parse(stored);
                let pool = this.pools.get(poolKey);
                if (!pool) {
                    pool = new Map();
                    this.pools.set(poolKey, pool);
                }
                data.forEach(({ text, translation }) => {
                    pool?.set(text, translation);
                });
                this.loadedCombinations.add(poolKey);
            }
        }
        catch (e) {
            console.warn('Failed to load translation cache from localStorage:', e);
        }
    }
    getStorageKey(fingerprint, toLang) {
        return `${this.crossTabOptions.storageKeyPrefix}${this.senseId}_${fingerprint}:${toLang}`;
    }
    saveToStorage(fingerprint, toLang) {
        if (typeof localStorage === 'undefined' || !this.crossTabOptions.enabled) {
            return;
        }
        const poolKey = this.getPoolKey(fingerprint, toLang);
        const storageKey = this.getStorageKey(fingerprint, toLang);
        try {
            const pool = this.pools.get(poolKey);
            const data = [];
            if (pool) {
                pool.forEach((translation, text) => {
                    data.push({ text, translation });
                });
            }
            localStorage.setItem(storageKey, JSON.stringify(data));
        }
        catch (e) {
            console.warn('Failed to save translation cache to localStorage:', e);
        }
    }
    broadcastUpdate(text, translation) {
        if (!this.broadcastChannel || !this.crossTabOptions.enabled) {
            return;
        }
        const fp = this.currentFingerprint || 'common';
        const toLang = this.currentToLang || 'en';
        const data = {
            result: this.getAllForFingerprint(fp, toLang),
            ...(text && translation && { text, translation }),
        };
        const message = {
            type: 'cache_update',
            senseId: this.senseId,
            fingerprint: this.currentFingerprint || undefined,
            data,
        };
        this.broadcastChannel.postMessage(message);
        this.saveToStorage(fp, toLang);
    }
    handleCacheUpdate(message) {
        const fp = message.fingerprint || 'common';
        const toLang = this.currentToLang || 'en';
        const poolKey = this.getPoolKey(fp, toLang);
        if (message.data?.result) {
            let pool = this.pools.get(poolKey);
            if (!pool) {
                pool = new Map();
                this.pools.set(poolKey, pool);
            }
            pool.clear();
            message.data.result.forEach(({ text, translation }) => {
                // Skip empty keys or error placeholder keys
                if (!text || text === 'error') {
                    return;
                }
                pool.set(text, translation);
            });
            this.loadedCombinations.add(poolKey);
        }
        if (message.data?.text && message.data?.translation) {
            // Skip empty keys or error placeholder keys
            if (!message.data.text || message.data.text === 'error') {
                return;
            }
            const pool = this.pools.get(poolKey) || new Map();
            pool.set(message.data.text, message.data.translation);
            this.pools.set(poolKey, pool);
            this.saveToStorage(fp, toLang);
        }
    }
    handleCacheClear(message) {
        const fp = message.fingerprint || 'common';
        {
            this.clearFingerprint(fp);
        }
    }
    handleInitialSyncRequest() {
        this.broadcastUpdate();
    }
    queueTranslationRequest(request) {
        const key = `${request.text}-${request.fingerprint || 'common'}`;
        const existingPending = this.pendingResolutions[key];
        if (existingPending) {
            return new Promise((resolve, reject) => {
                existingPending.resolveList.push(resolve);
                existingPending.rejectList.push(reject);
            });
        }
        return new Promise((resolve, reject) => {
            const queuedReq = {
                ...request,
                resolveFunction: resolve,
                rejectFunction: reject,
            };
            this.queuedRequests.push(queuedReq);
            this.pendingResolutions[key] = {
                resolve: resolve,
                reject: reject,
                resolveList: [resolve],
                rejectList: [reject],
            };
        });
    }
    async processQueuedRequests(maxRetries = 3, retryDelayMs = 1000) {
        if (this.queuedRequests.length === 0) {
            this.loading = false;
            return;
        }
        console.log(`[TranslationPool] Processing ${this.queuedRequests.length} queued translation requests...`);
        this.loading = false;
        const requestsToProcess = [...this.queuedRequests];
        this.queuedRequests = [];
        const processWithRetry = async (req, attempt = 0) => {
            try {
                const lookup = this.lookup(req.text, req.fingerprint);
                if (lookup.found) {
                    const response = await this.client.translateWithDetails(req.text, req.toLang, req.fromLang, req.fingerprint);
                    return { text: req.text, translation: response.translation[req.text] || req.text, success: true };
                }
                else {
                    const response = await this.client.translateWithDetails(req.text, req.toLang, req.fromLang, req.fingerprint);
                    return { text: req.text, translation: response.translation[req.text] || req.text, success: true };
                }
            }
            catch (error) {
                console.warn(`[TranslationPool] Request failed (attempt ${attempt + 1}/${maxRetries}):`, error.message);
                if (attempt < maxRetries - 1) {
                    await new Promise(resolve => setTimeout(resolve, retryDelayMs * (attempt + 1)));
                    return processWithRetry(req, attempt + 1);
                }
                console.error(`[TranslationPool] All retries failed for: "${req.text}", using original text`);
                return { text: req.text, translation: req.text, success: false };
            }
        };
        const promises = requestsToProcess.map(req => processWithRetry(req));
        const results = await Promise.all(promises);
        const successCount = results.filter(r => r.success).length;
        const failCount = results.length - successCount;
        results.forEach(({ text, translation }, index) => {
            this.addTranslation(text, translation);
            const queuedReq = requestsToProcess[index];
            if (queuedReq && queuedReq.resolveFunction) {
                const response = create(TranslateStreamResponseSchema, {
                    originalText: text,
                    translation: { [text]: translation },
                    timestamp: BigInt(Date.now()),
                    finished: true,
                    batchIndex: 0,
                });
                queuedReq.resolveFunction(response);
                const key = `${text}-${queuedReq.fingerprint || 'common'}`;
                delete this.pendingResolutions[key];
                if (this.onTranslationUpdated) {
                    this.onTranslationUpdated(text, translation);
                }
            }
        });
        requestsToProcess.forEach((queuedReq, index) => {
            if (!results[index].success && queuedReq.rejectFunction) {
                const error = new Error(`Translation failed for: ${queuedReq.text}`);
                queuedReq.rejectFunction(error);
                const key = `${queuedReq.text}-${queuedReq.fingerprint || 'common'}`;
                delete this.pendingResolutions[key];
            }
        });
        this.broadcastUpdate();
        console.log(`[TranslationPool] Completed processing ${results.length} queued requests (${successCount} success, ${failCount} failed)`);
        if (this.onQueueProcessed) {
            this.onQueueProcessed(results.length);
        }
        if (failCount > 0) {
            console.warn(`[TranslationPool] ${failCount} requests failed after ${maxRetries} retries`);
        }
    }
    hasQueuedRequests() {
        return this.queuedRequests.length > 0;
    }
    clearQueuedRequests() {
        console.log(`Clearing ${this.queuedRequests.length} queued requests`);
        this.queuedRequests = [];
        this.pendingResolutions = {};
    }
    isLoading() {
        return this.loading;
    }
    isLanguageLoaded(fingerprint, toLang) {
        if (toLang === undefined) {
            const checkedToLang = fingerprint;
            for (const key of this.loadedCombinations) {
                if (key.endsWith(`:${checkedToLang}`)) {
                    return true;
                }
            }
            return false;
        }
        const poolKey = this.getPoolKey(fingerprint, toLang);
        return this.loadedCombinations.has(poolKey);
    }
    async initialize(toLang) {
        if (this.loading) {
            return;
        }
        this.loading = true;
        this.currentToLang = toLang;
        try {
            console.log(`[TranslationPool] Starting pool initialization... (toLang: ${toLang})`);
            const commonPoolKey = this.getPoolKey('common', toLang);
            if (!this.loadedCombinations.has(commonPoolKey)) {
                await this.loadFingerprintTranslations('common', undefined, toLang);
                console.log(`[TranslationPool] Common translations loaded for ${toLang}`);
            }
            if (this.currentFingerprint) {
                const fpPoolKey = this.getPoolKey(this.currentFingerprint, toLang);
                if (!this.loadedCombinations.has(fpPoolKey)) {
                    await this.loadFingerprintTranslations(this.currentFingerprint, this.currentFingerprint, toLang);
                    console.log(`[TranslationPool] ${this.currentFingerprint} translations loaded for ${toLang}`);
                }
            }
            this.broadcastUpdate();
            console.log(`[TranslationPool] Pool initialization completed for ${toLang}`);
            if (this.onPoolInitialized) {
                this.onPoolInitialized();
            }
            await this.processQueuedRequests();
        }
        finally {
            this.loading = false;
        }
    }
    async loadFingerprintTranslations(fp, fingerprint, toLang) {
        const poolKey = this.getPoolKey(fp, toLang);
        this.loadLanguageFromStorage(fp, toLang);
        let pool = this.pools.get(poolKey);
        if (!pool) {
            pool = new Map();
            this.pools.set(poolKey, pool);
        }
        let updatedCount = 0;
        let addedCount = 0;
        const req = create(TranslateStreamRequestSchema, {
            senseId: this.senseId,
            fingerprint,
            dstLang: toLang,
        });
        if (fingerprint) {
            req.fingerprint = fingerprint;
        }
        const stream = this.client.client.translateStream(req);
        for await (const response of stream) {
            if (!response.translation)
                continue;
            Object.entries(response.translation).forEach(([text, translate]) => {
                // Skip empty keys or error placeholder keys
                if (!text || text === 'error') {
                    return;
                }
                const translateStr = translate;
                const existing = pool?.get(text);
                if (existing === undefined) {
                    addedCount++;
                }
                else if (existing !== translateStr) {
                    updatedCount++;
                }
                pool?.set(text, translateStr);
                const key = `${text}-${fp}`;
                if (this.pendingResolutions[key]) {
                    const responseObj = create(TranslateStreamResponseSchema, {
                        originalText: text,
                        translation: { [text]: translateStr },
                        timestamp: BigInt(Date.now()),
                        finished: true,
                        batchIndex: 0,
                    });
                    this.pendingResolutions[key].resolveList.forEach(resolve => resolve(responseObj));
                    delete this.pendingResolutions[key];
                }
                if (fp !== 'common') {
                    const commonKey = `${text}-common`;
                    if (this.pendingResolutions[commonKey]) {
                        const responseObj = create(TranslateStreamResponseSchema, {
                            originalText: text,
                            translation: { [text]: translateStr },
                            timestamp: BigInt(Date.now()),
                            finished: true,
                            batchIndex: 0,
                        });
                        this.pendingResolutions[commonKey].resolveList.forEach(resolve => resolve(responseObj));
                        delete this.pendingResolutions[commonKey];
                    }
                }
                if (this.onTranslationLoaded) {
                    this.onTranslationLoaded(text, translateStr);
                }
            });
        }
        this.saveToStorage(fp, toLang);
        if (updatedCount > 0 || addedCount > 0) {
            console.log(`[TranslationPool] Loaded ${fp}:${toLang} - added ${addedCount}, updated ${updatedCount} from remote`);
        }
        this.loadedCombinations.add(poolKey);
    }
    addPreloadedTranslations(preloaded) {
        Object.entries(preloaded).forEach(([fingerprint, langMap]) => {
            Object.entries(langMap).forEach(([toLang, translations]) => {
                const poolKey = this.getPoolKey(fingerprint, toLang);
                let pool = this.pools.get(poolKey);
                if (!pool) {
                    pool = new Map();
                    this.pools.set(poolKey, pool);
                }
                Object.entries(translations).forEach(([text, translation]) => {
                    pool.set(text, translation);
                    if (this.onTranslationLoaded) {
                        this.onTranslationLoaded(text, translation);
                    }
                });
                this.loadedCombinations.add(poolKey);
                this.saveToStorage(fingerprint, toLang);
            });
        });
        this.broadcastUpdate();
    }
    addTranslation(text, translation) {
        const fp = this.currentFingerprint || 'common';
        const toLang = this.currentToLang || 'en';
        const poolKey = this.getPoolKey(fp, toLang);
        let pool = this.pools.get(poolKey);
        if (!pool) {
            pool = new Map();
            this.pools.set(poolKey, pool);
        }
        pool.set(text, translation);
        this.saveToStorage(fp, toLang);
        this.broadcastUpdate(text, translation);
    }
    addTranslationToFingerprint(text, translation, fingerprint, toLang) {
        const poolKey = this.getPoolKey(fingerprint, toLang);
        let pool = this.pools.get(poolKey);
        if (!pool) {
            pool = new Map();
            this.pools.set(poolKey, pool);
        }
        pool.set(text, translation);
        this.saveToStorage(fingerprint, toLang);
        this.broadcastUpdate(text, translation);
    }
    /**
     * Alias for addTranslationToFingerprint - convenient manual caching
     * Parameter order: text, fingerprint, translation, toLang
     */
    put(text, fingerprint, translation, toLang) {
        // Set current language if not set, so subsequent lookups work correctly
        if (!this.currentToLang) {
            this.currentToLang = toLang;
        }
        this.addTranslationToFingerprint(text, translation, fingerprint, toLang);
    }
    lookup(text, fingerprint, toLang) {
        const fp = fingerprint || this.currentFingerprint || 'common';
        const lang = toLang || this.currentToLang || 'en';
        const poolKey = this.getPoolKey(fp, lang);
        const pool = this.pools.get(poolKey);
        if (pool && pool.has(text)) {
            return { found: true, fromCache: true, translation: pool.get(text) };
        }
        if (fp !== 'common') {
            const commonPoolKey = this.getPoolKey('common', lang);
            const commonPool = this.pools.get(commonPoolKey);
            if (commonPool && commonPool.has(text)) {
                return { found: true, fromCache: true, translation: commonPool.get(text) };
            }
        }
        return { found: false, fromCache: false };
    }
    /**
     * Check if any translation exists for the current language
     * This can be used to determine if translation pool has any translations
     * @returns boolean true if pool has any translations for current language
     */
    hasAnyTranslations() {
        const toLang = this.currentToLang;
        if (!toLang)
            return false;
        for (const [poolKey, pool] of this.pools.entries()) {
            if (poolKey.endsWith(`:${toLang}`) && pool.size > 0) {
                return true;
            }
        }
        return false;
    }
    /**
     * Get the number of cached translations for a specific fingerprint and language
     * If language is not specified, uses current language
     * If fingerprint is not specified, returns total size across all fingerprints for current language
     * @param fingerprint Fingerprint (optional, returns total if not specified)
     * @param toLang Target language (uses current if not specified)
     * @returns Number of cached translations
     */
    getCacheSize(fingerprint, toLang) {
        const targetLang = toLang || this.currentToLang || 'en';
        // If fingerprint is specified, return size for that specific pool
        if (fingerprint) {
            const poolKey = this.getPoolKey(fingerprint, targetLang);
            const pool = this.pools.get(poolKey);
            return pool?.size || 0;
        }
        // If no fingerprint specified, return total size across all fingerprints for current language
        let totalSize = 0;
        for (const [poolKey, pool] of this.pools.entries()) {
            if (poolKey.endsWith(`:${targetLang}`)) {
                totalSize += pool.size;
            }
        }
        return totalSize;
    }
    /**
     * Get all translations for a fingerprint+language combination
     * @param fingerprint Fingerprint ('common' or specific)
     * @param toLang Target language
     * @returns Array of {text, translation}
     */
    getAllForFingerprint(fingerprint, toLang) {
        const poolKey = this.getPoolKey(fingerprint, toLang);
        const pool = this.pools.get(poolKey);
        const result = [];
        if (pool) {
            pool.forEach((translation, text) => {
                result.push({ text, translation });
            });
        }
        return result;
    }
    /**
     * Get all cached translations for current language across all fingerprints
     * @returns Map of all cached translations with full keys
     */
    getAllForCurrentLanguage() {
        const toLang = this.currentToLang;
        if (!toLang)
            return new Map();
        const result = new Map();
        for (const [poolKey, pool] of this.pools.entries()) {
            if (poolKey.endsWith(`:${toLang}`)) {
                result.set(poolKey, new Map(pool));
            }
        }
        return result;
    }
    /**
     * Clear all translations for a specific fingerprint
     * @param fingerprint Fingerprint to clear
     */
    clearFingerprint(fingerprint) {
        const toLang = this.currentToLang;
        if (!toLang) {
            // If no language set, just remove the pool keys from memory
            for (const key of this.pools.keys()) {
                if (key.startsWith(`${fingerprint}:`)) {
                    this.pools.delete(key);
                    this.loadedCombinations.delete(key);
                }
            }
            return;
        }
        const poolKey = this.getPoolKey(fingerprint, toLang);
        this.pools.delete(poolKey);
        this.loadedCombinations.delete(poolKey);
        if (this.crossTabOptions.enabled) {
            const storageKey = this.getStorageKey(fingerprint, toLang);
            try {
                localStorage.removeItem(storageKey);
            }
            catch (e) {
                console.warn('Failed to remove from localStorage:', e);
            }
        }
        this.clearQueuedRequests();
    }
    /**
     * Clear all cached translations for all fingerprints and languages
     * Does not affect preloaded translations unless they were added after initialization
     */
    clearAll() {
        this.pools.clear();
        this.loadedCombinations.clear();
        this.clearQueuedRequests();
        if (typeof localStorage !== 'undefined' && this.crossTabOptions.enabled) {
            const prefix = `${this.crossTabOptions.storageKeyPrefix}${this.senseId}_`;
            const keysToRemove = [];
            for (let i = 0; i < localStorage.length; i++) {
                const key = localStorage.key(i);
                if (key && key.startsWith(prefix)) {
                    keysToRemove.push(key);
                }
            }
            keysToRemove.forEach(key => localStorage.removeItem(key));
        }
        console.log('[TranslationPool] Cleared all cached translations');
    }
    /**
     * Alias for clearAll - clear entire cache
     */
    clearCache() {
        this.clearAll();
    }
    /**
     * Set the current active fingerprint
     * Automatically loads the new fingerprint's translations for the current language
     * @param fingerprint New fingerprint to set
     * @param toLang Target language (optional, uses currentToLang if not provided)
     */
    async setCurrentFingerprint(fingerprint, toLang) {
        const targetLang = toLang || this.currentToLang;
        const oldFingerprint = this.currentFingerprint;
        this.currentFingerprint = fingerprint;
        this.currentLanguageVersion++;
        console.log(`[TranslationPool] Changed current fingerprint from ${oldFingerprint} to: ${fingerprint}`);
        // If we have a target language and the fingerprint changed, load the new fingerprint's translations
        if (targetLang && fingerprint && fingerprint !== oldFingerprint) {
            const fpPoolKey = this.getPoolKey(fingerprint, targetLang);
            if (!this.loadedCombinations.has(fpPoolKey)) {
                console.log(`[TranslationPool] Auto-loading translations for new fingerprint: ${fingerprint}`);
                await this.loadFingerprintTranslations(fingerprint, fingerprint, targetLang);
                console.log(`[TranslationPool] Loaded translations for fingerprint: ${fingerprint} (${targetLang})`);
            }
        }
    }
    /**
     * Get current active fingerprint
     * @returns Current fingerprint or null
     */
    getCurrentFingerprint() {
        return this.currentFingerprint;
    }
    /**
     * Start background update checker that periodically checks for stale translations
     * Only runs if background update is enabled
     */
    startBackgroundUpdateChecker() {
        if (!this.backgroundUpdateOptions.enabled || typeof window === 'undefined') {
            return;
        }
        if (this.backgroundUpdateTimer) {
            clearInterval(this.backgroundUpdateTimer);
        }
        this.backgroundUpdateTimer = setInterval(() => {
            this.checkForStaleTranslations();
        }, this.backgroundUpdateOptions.intervalMs);
        console.log(`[TranslationPool] Started background update checker every ${this.backgroundUpdateOptions.intervalMs}ms`);
    }
    /**
     * Stop background update checker
     */
    stopBackgroundUpdateChecker() {
        if (this.backgroundUpdateTimer) {
            clearInterval(this.backgroundUpdateTimer);
            this.backgroundUpdateTimer = null;
            console.log('[TranslationPool] Stopped background update checker');
        }
    }
    /**
     * Check for stale translations and request updates
     * This is called automatically by the background timer
     */
    checkForStaleTranslations() {
        if (!this.updateCallback || !this.currentToLang) {
            return;
        }
        const now = Date.now();
        const staleThreshold = this.backgroundUpdateOptions.staleThresholdMs;
        const staleEntries = [];
        this.entryMetadata.forEach((metadata, key) => {
            if (now - metadata.lastUpdated > staleThreshold) {
                const [text, toLang] = key.split('|');
                staleEntries.push({ text, toLang });
            }
        });
        if (staleEntries.length === 0) {
            return;
        }
        const batchSize = this.backgroundUpdateOptions.batchSize;
        const staleToProcess = staleEntries.slice(0, batchSize);
        staleToProcess.forEach(({ text, toLang }) => {
            if (this.updateCallback) {
                this.updateCallback(text, toLang);
            }
        });
        console.log(`[TranslationPool] Triggered update for ${staleToProcess.length} stale translations`);
    }
    /**
     * Update metadata for a cache entry when it's fetched from server
     * @param text Original text
     * @param toLang Target language
     */
    updateEntryMetadata(text, toLang) {
        const key = `${text}|${toLang}`;
        const existing = this.entryMetadata.get(key);
        this.entryMetadata.set(key, {
            lastUpdated: Date.now(),
            version: (existing?.version || 0) + 1,
        });
    }
}
class TranslationClient {
    baseUrl;
    token;
    client;
    transport;
    pool;
    senseId;
    defaultFromLang;
    options;
    constructor(options) {
        this.options = options;
        // If baseUrl is not provided, use the default production endpoint
        // The baseUrl should include the API path prefix for Connect RPC
        // Expected format: https://api.hottol.com/laker/api/v1/translate/rpc/stream
        const defaultBaseUrl = "https://api.hottol.com/laker/api/v1/translate/rpc/stream";
        this.baseUrl = options.baseUrl
            ? options.baseUrl.replace(/\/$/, "") + "/api/v1/translate/rpc/stream"
            : defaultBaseUrl;
        this.token = options.token;
        const baseUrl = this.baseUrl;
        // Create Connect transport with api-key-token header if token provided
        this.transport = createConnectTransport({
            baseUrl,
            useHttpGet: false,
            interceptors: this.token ? [
                (next) => async (req) => {
                    req.header.set('api-key-token', this.token);
                    return await next(req);
                },
            ] : undefined,
        });
        this.client = createClient(TranslationService, this.transport);
        this.senseId = options.senseId;
        this.defaultFromLang = options.defaultFromLang || 'en';
        // Create and manage translation pool internally
        this.pool = new TranslationPool(this, this.senseId, {
            crossTab: options.crossTab,
            backgroundUpdate: options.backgroundUpdate,
            persistentStorage: options.persistentStorage,
        });
    }
    /**
     * Simple one-shot translation - automatically handles caching, initialization, and queuing
     * @param text Original text to translate
     * @param toLang Target language code
     * @param fromLang Source language code (optional, defaults to client default)
     * @param fingerprint Text fingerprint for domain-specific translations
     * @returns Promise with translated text (resolves when translation completes)
     */
    async translate(text, toLang, fromLang, fingerprint) {
        // Use defaults if not provided
        const actualFromLang = fromLang || this.defaultFromLang;
        const actualFingerprint = fingerprint || 'common';
        // Check cache first
        const lookup = this.pool.lookup(text, actualFingerprint);
        if (lookup.found && lookup.translation) {
            return lookup.translation;
        }
        // If language not initialized, initialize it first
        if (!this.pool.isLanguageLoaded(actualFingerprint, toLang)) {
            await this.pool.initialize(toLang);
        }
        // Queue the request and wait for completion
        const response = await this.pool.queueTranslationRequest({
            text,
            toLang,
            fromLang: actualFromLang,
            fingerprint: actualFingerprint,
        });
        return response.translation[text] || text;
    }
    /**
     * Translate text with full response details (direct API call, no caching)
     * @param text Original text to translate
     * @param toLang Target language code
     * @param fromLang Source language code (optional, defaults to client default)
     * @param fingerprint Text fingerprint for domain-specific translations
     * @returns Promise with complete translation response
     */
    async translateWithDetails(text, toLang, fromLang, fingerprint) {
        // Use TranslateStream for translation - get the first response from the stream
        const req = create(TranslateStreamRequestSchema, {
            text,
            toLang,
        });
        if (fromLang) {
            req.fromLang = fromLang;
        }
        if (fingerprint) {
            req.fingerprint = fingerprint;
        }
        // Get the first (and likely only) response from the stream
        const stream = this.client.translateStream(req);
        for await (const response of stream) {
            return response;
        }
        // If no response, throw an error
        throw new Error('No translation response received');
    }
    /**
     * Stream translation batches for a semantic sense
     * Uses native Connect RPC streaming with true multiplexing
     * @param senseId Semantic sense ID
     * @param dstLang Target language
     * @param fingerprint Optional fingerprint for specific domain
     * @param batchSize Optional batch size (default 500)
     * @returns Async iterable stream of translation responses
     */
    translateStream(senseId, dstLang, fingerprint) {
        const req = create(TranslateStreamRequestSchema, {
            senseId,
            dstLang,
        });
        if (fingerprint) {
            req.fingerprint = fingerprint;
        }
        return this.client.translateStream(req);
    }
    /**
     * Get paged list of translations for a semantic sense with optional filtering
     * @param options Request options including filtering, pagination
     * @returns Promise with filtered, paged translations
     */
    async getSenseTranslations(options) {
        const req = create(GetSenseTranslateRequestSchema, {
            senseId: options.senseId,
        });
        if (options.fingerprint !== undefined) {
            req.fingerprint = options.fingerprint;
        }
        if (options.page !== undefined) {
            req.page = options.page;
        }
        if (options.pageSize !== undefined) {
            req.pageSize = options.pageSize;
        }
        // Note: srcLang, dstLang, dstLangs are not supported in GetSenseTranslateRequest
        // These fields are only available in TranslateStreamRequest
        return (await this.client.getSenseTranslate(req));
    }
    /**
     * Create a translation pool for preloading and caching translations
     * @param senseId Semantic sense ID to create pool for
     * @param options Pool configuration options
     * @returns TranslationPool instance
     */
    createPool(senseId, options) {
        return new TranslationPool(this, senseId, options);
    }
    /**
     * Get the underlying Connect RPC client for advanced use
     * @returns The client instance
     */
    getClient() {
        return this.client;
    }
    /**
     * Get information about the current sense
     * @returns Object containing sense ID and default settings
     */
    getSenseInfo() {
        return {
            senseId: this.senseId,
            defaultFromLang: this.defaultFromLang,
        };
    }
}

export { TranslationClient, TranslationPool, TranslationClient as default, extractTemplate };
//# sourceMappingURL=translation-client.js.map
